### ISSUE TITLE
[integration] PagerDuty Webhook

### ISSUE THREAD

**Issue by agardnerIT** [keptn/integrations#18]
Investigate (and if possible) develop [webhook service](https://github.com/keptn/keptn/tree/master/webhook-service)  based integration (notification / fire and forget) integration with PagerDuty.

A full bi-directional PagerDuty integration is out of scope for this ticket. That requirement would be best suited to a "full" Keptn service.

## Definition of Done

- [ ] Either that PagerDuty webhook integration using [webhook service](https://github.com/keptn/keptn/tree/master/webhook-service) is NOT achievable OR
- [ ] PagerDuty webhook integration code sample given on ArtifactHub and thus listed on Keptn.sh

If you need this integration, click the thumbs up emoji.
If you are willing to "sponsor" (ie. support) the development of this integration, click the heart emoji.

**Comment by afzal442** [comment]
Hi, I would like to look into this. Thanks

**Comment by afzal442** [comment]
Hi,
Could you elaborate a little more about `integration (notification / fire and forget) integration `?

![image](https://user-images.githubusercontent.com/11625672/173984844-13e01406-dd19-48a7-8ad2-232b4e88db73.png)

Any example regarding that `URL?` Thanks

**Comment by afzal442** [comment]
Hi, I was wondering what I need to do further with that. I think, I am now able to get the response using GET API request triggered by webhook service after subscribed for an event.

**Comment by afzal442** [comment]
Investigation on [PagerDuty API](https://developer.pagerduty.com/api-reference/b3A6Mjc0ODI2Nw-send-an-event-to-pager-duty)
Part 1 

```json
{
curl --request POST \
  --url https://events.pagerduty.com/v2/enqueue \
  --header 'Content-Type: application/json' \
  --data '{
	"payload": {
		"summary": "My Test dg1",
		"severity": "high",
		"source": "sh.keptn.triggered.event"
	},
	"routing_key": "92877d39e483490ac09a20101967e88e",
	"dedup_key": "dtg/svc",
	"event_action": "trigger",
	"client": "Sample Monitoring Service",
	"client_url": "https://datadog.service.com"
}'
}
```

Part 2

```json
curl --request POST \
  --url https://api.pagerduty.com/incidents \
  --header 'Accept: application/vnd.pagerduty+json;version=2' \
  --header 'Authorization: Token token=u+jAbd1s9vZAysEnxU1w' \
  --header 'Content-Type: application/json' \
  --header 'From: b113053@iiit-bh.ac.in' \
  --data '{
  "incident": {
    "type": "incident",
    "title": "The server is on fire.",
    "service": {
      "id": "PP7DGG2",
      "type": "service_reference"
    },
    "priority": {
      "id": "P53ZZH5",
      "type": "priority_reference"
    },
    "urgency": "high",
    "incident_key": "92877d39e483490ac09a20101967e88e",
    "body": {
      "type": "incident_body",
      "details": "A disk is getting full on this machine. You should investigate what is causing the disk to fill, and ensure that there is an automated process in place for ensuring data is rotated (eg. logs should have logrotate around them). If data is expected to stay on this disk forever, you should start planning to scale up to a larger disk."
    },
    "escalation_policy": {
      "id": "PNJ2H9R",
      "type": "escalation_policy_reference"
    }
  }
}'
```

**Comment by agardnerIT** [comment]
@johannes-b please assign to @afzal442

**Comment by afzal442** [comment]
Related links 
https://docs.robusta.dev/master/catalog/sinks/PagerDuty.html

https://www.youtube.com/watch?v=Fckop7DmMNI
