### ISSUE TITLE
New Integration: Keptn Plugin for Backstage

### ISSUE THREAD

**Issue by oleg-nenashev** [keptn/integrations#19]
[Backstage](https://backstage.io/) is an open platform for building developer portals. As the website states, "powered by a centralized software catalog, Backstage restores order to your infrastructure and enables your product teams to ship high-quality code quickly — without compromising autonomy".

It would be nice if it was possible to provide Keptn integration for this portal so that Keptn could be connected as many other tools. See all [Backstage Plugins](https://backstage.io/plugins).

## References

* Working group: `#wg-backstage-integrations` on Slack
* Plugin: https://github.com/keptn-sandbox/backstage-plugin-keptn
* GSoC project idea: https://github.com/keptn/community/blob/main/mentorship/gsoc/2022/project-ideas.md#keptn-backstage-plugin 

## Possible solutions

* A specialized plugin for Keptn using Keptn REST API and/or CLI
* A Unified plugin for Keptn and other CI/CD tools, e.g. implemented on the top of the Cloud Events / CD Events standard. If so, would be nice to sync-up with @timja @salaboy so that we could figure out feasibility of such an approach for some use-cases

## Notes

* It could be a good Google Summer of Code project
* [Discussion in Keptn Slack](https://keptn.slack.com/archives/CFH319TPE/p1639987497191600)

**Comment by 120EE0980** [comment]
Helloo..I want to contribute to this project idea as part of gsoc2023. I have been doing small projects on react and javascript.
Hey @bradmccoydev can you help me get started in contributing..

**Comment by Cvr421** [comment]
Hello @bradmccoydev   I want to work on this project as part of 2023 Gsoc .  I have work on multiple Javascript and react projects and I have also experience with the kubernetes and docker . so I need help to getting started contributing...

**Comment by prateek041** [comment]
I am interested in this issue and planning to work on it this summer, for GSoC 2023. 

I understand what the first **Possible Solution** means. I went through their docs and have a gist of how it could be done via a Keptn Plugin, but, could you give more details/briefing on what the second suggests ?

@oleg-nenashev @bradmccoydev

**Comment by thisthat** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
