### ISSUE TITLE
Provide integration with Github actions

### ISSUE THREAD

**Issue by jetzlstorfer** [keptn/integrations#24]
Provide an integration with [Github actions](https://github.com/features/actions).

The desired solution should kick-off a CI workflow with Github actions (see https://docs.github.com/en/free-pro-team@latest/actions/guides/about-continuous-integration for reference) and once the container image is built, the integration should trigger Keptn to continue kick-off the deployment, testing, evaluation, and potential promotion of the built image.
Therefore, the Github integration has to send a `sh.keptn.event.configuration.change` to Keptn.

**Definition of Done**

- [ ] repo created in the keptn-sandbox organization and code contributed to this repo
- [ ] depending on the implementation: have a structured and detailed README.md how to achieve this or have an implementation that can be used out-of-the-box (some research might be needed what can be done here)
- [ ] integration sends a `sh.keptn.event.configuration.change` after the image is built from the Github action integration, which triggers a deployment with Keptn

**Comment by agardnerIT** [comment]
Can this be used? https://artifacthub.io/packages/keptn/keptn-integrations/githubaction
