### ISSUE TITLE
[integration] JIRA Webhook Integration

### ISSUE THREAD

**Issue by agardnerIT** [keptn/integrations#5]
Investigate possibility (and create) a webhook service based integration for JIRA which would (if technically possible), retire the [JIRA service](https://github.com/keptn-sandbox/jira-service) and make things much simpler to update in the future: if / when JIRA change their end, only the payload needs to be updated rather than a rework of an entire Keptn service.

Intention here is to be a JIRA notification service (ie. fire and forget) not a fully-fledged bi-directional service. Complex logic like that is best built into a "full" Keptn service.

## Definition of Done

- [ ] Either that JIRA is not able to be used with the webhook service OR
- [ ] JIRA webhook integration sample code given, added to the artifacthub listing on keptn.sh and [JIRA service](https://github.com/keptn-sandbox/jira-service) is listed as deprecated

If you need this integration, click the thumbs up emoji.
If you are willing to "sponsor" (not necessarily financial: support, advise of co-develop) this integration, click the heart emoji.

**Comment by agardnerIT** [comment]
@mehabhalodiya are you still interested in working on this?

**Comment by mehabhalodiya** [comment]
@agardnerIT I am interested to work but I guess I will not able to work because as a part of GSoC'22, I am working on #28 and #15 🙂

**Comment by agardnerIT** [comment]
@johannes-b  please assign to @afzal442
