### ISSUE TITLE
[integration] Grafana Tanka / Jsonnet

### ISSUE THREAD

**Issue by nanofly0** [keptn/integrations#51]
### Tool / Product Name

Grafana Tanka / Jsonnet

### Goal

```shell
I want Keptn to be able to deploy applications defined as Jsonnet configuration instead of Helm.
Optionally Keptn can modify my Jsonnet configuration for Canaries/Blue-Green deployments.
```

### #help-integrations on Slack

- [X] Yes

### No Existing Integrations

- [X] Yes

### Assisted

Yes

**Comment by agardnerIT** [comment]
Thanks for creating this. I have zero experience with either of these, but as I understand [this page](https://jsonnet.org/learning/getting_started.html), you can run `jsonnet -e { "hello": "world" }` or `jsonnet -e file.jsonnet`

If that's the case, I'd suggest looking the the [job executor service (aka JES)](https://github.com/keptn-contrib/job-executor-service) and having it run an image containing jsonnet ([bitnami/jsonnet](https://hub.docker.com/r/bitnami/jsonnet)?).

Look at the [file handling section](https://github.com/keptn-contrib/job-executor-service/blob/main/docs/FEATURES.md#file-handling) of JES. Files from your Git repo can be copied into the jsonnet container when the job starts and they become available at `/keptn/yourFile.jsonnet`.

Here's an example JES config file (and repo structure for you to follow) which hopefully gives you some hints: https://github.com/agardnerIT/keptninfracost2/blob/dev/service1/job/config.yaml

**Comment by agardnerIT** [comment]
@lucasclerissepro are you still able to work on this integration?
