### ISSUE TITLE
[integration] Tracetest integration

### ISSUE THREAD

**Issue by danielbdias** [keptn/integrations#62]
### Tool / Product Name

Tracetest

### Goal

```shell
Hi folks! Based on the discussion on this issue: https://github.com/keptn/lifecycle-toolkit/issues/508 , here at Tracetest.io we prepared documentation to integrate Tracetest into Keptn and use it in the testing phases.

The documentation can be seen here: https://github.com/kubeshop/tracetest/tree/main/examples/keptn-integration
```

### #help-integrations on Slack

- [X] Yes

### No Existing Integrations

- [X] Yes

### Assisted

Yes

**Comment by danielbdias** [comment]
@thisthat @agardnerIT what do you think about this documentation, it makes sense? Feel free to ask us for any additional info about that.

**Comment by ashutosh887** [comment]
@danielbdias I would like to work on this

**Comment by danielbdias** [comment]
Hi @ashutosh887, how are you? It is very good to know that 😄 , recently we released the [first version](https://artifacthub.io/packages/keptn/keptn-integrations/tracetest) of this integration, and we plan to update it soon! 
We have thought about adding support for more telemetry on Tracetests, allowing users to run a test and evaluate it on Keptn in two ways:
1. By updating this integration to use the Tracetest + k6 integration;
2. By emitting telemetry during the test run, as @agardnerIT did on his previous integration (#48 )

Feel free to ping us to ask for any help on [Tracetest Discord](https://discord.gg/6zupCZFQbe) or in [Keptn Slack](https://keptn.sh/community/) on #keptn-integrations Slack channel!

**Comment by thisthat** [comment]
Hey @danielbdias, sorry for the late reply. The documentation looks good to me 👍

**Comment by thisthat** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
