### ISSUE TITLE
[integration] Botkube Integration 

### ISSUE THREAD

**Issue by mashby2022** [keptn/integrations#63]
### Tool / Product Name

Botkube

### Goal

```shell
Hi all! The Botkube team has prepared a Botkube x Keptn Plug-in that uses web hook service. A step by step walk through can be seen here: https://botkube.io/blog/implementing-your-own-botkube-plugin-a-real-life-use-case @huseyinbabal
```

### #help-integrations on Slack

- [X] Yes

### No Existing Integrations

- [X] Yes

### Assisted

Yes

### Any other info?

Keptn plug in is already made

**Comment by thisthat** [comment]
Since Keptn V1 has reached EOL on December 22nd, 2023, this issue has been closed.
